### ISSUE TITLE
put it to f-droid

### ISSUE THREAD

**Issue by silvio** [vector-im/vector-android#110]
Would be great to see your software on f-droid ...

**Comment by ylecollen** [comment]
Should be done soon

**Comment by silvio** [comment]
juhuu!

**Comment by sim6** [comment]
I can't see it :(

**Comment by pganssle** [comment]
@ylecollen This does not seem to be done. What is the name of the app in F-Droid?

**Comment by ara4n** [comment]
There seem to be problems getting the APK itself posted on Fdroid. 
@oddvar, what's the story?

**Comment by ylecollen** [comment]
I don't find Vector on F-droid.

**Comment by oddvar** [comment]
hey, there were some issues in getting the build working, but that's now all been fixed.

Finally we have https://f-droid.org/repository/browse/?fdfilter=vector&fdid=im.vector.alpha !
