### ISSUE TITLE
Room search: Room preview should be used when user selects a public room that he did not join yet

### ISSUE THREAD

**Issue by giomfo** [vector-im/vector-android#138]
Presently the user auto joins the selected room which is not really nice.

To reproduce:

1- leave #test:matrix.org
2- search room with pattern "test"
3- select #test:matrix.org room from Directory section
4- user auto join the room NOK- a room preview is expected here with the join option

**Comment by ylecollen** [comment]
should be fixed in
https://github.com/vector-im/vector-android/commit/328c1d50c48019ae59bc9a47a6b30880ef78b39f
