### ISSUE TITLE
Image scaling algorithm choice could use some work

### ISSUE THREAD

**Issue by Xe** [vector-im/vector-android#144]
![](http://puu.sh/oYYkm/49613e8cc6.png)

**Comment by ylecollen** [comment]
Could you explain us your issue / request ?

I don't understand what you expect.

**Comment by ylecollen** [comment]
I assume this issue was triggered because the rounded avatar has a bad quality.

**Comment by ylecollen** [comment]
Should be fixed in 
https://github.com/vector-im/vector-android/commit/fb392750c98d9cc5963466e6080f22452f759fd9
