### ISSUE TITLE
Room screen: display edit menu on long press on message

### ISSUE THREAD

**Issue by giomfo** [vector-im/vector-android#153]

**Comment by ylecollen** [comment]
Fixed in 
https://github.com/vector-im/vector-android/commit/b43079f2e602f48a0e7dee3bcb8703a6683b16da

**Comment by iav** [comment]
But where "edit"?

**Comment by iav** [comment]
![tmp_20920-screenshot_2016-05-26-19-52-32-482951514](https://cloud.githubusercontent.com/assets/325961/15582860/bedc0c18-237b-11e6-832e-91496fb8528b.png)
