### ISSUE TITLE
Expanded header: Add shortcuts on avatar and room name

### ISSUE THREAD

**Issue by giomfo** [vector-im/vector-android#162]
When user has enough power level:
- Touch on avatar should open directly the media picker.
Shall we return on room details when a picture is selected? 
What should we do when picker is dismissed?

- Touch on room name should open room details by editing the room name.

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/b8c608b252740c7d7db3706e941a9216482f9047

-> it opens a dialog instead of switching to the dedicated room settings page because i did not find a way to give the focus to the dedicated settings entry
