### ISSUE TITLE
Dismiss notifications for messages already read on other devices

### ISSUE THREAD

**Issue by Vifon** [vector-im/vector-android#164]
**What I do**

I receive a new message. I read that message with https://vector.im and then look at my phone with the Vector Android App installed.

**What I expect**

The notification about the message I've just read should disappear when read on any client.

**What currently happens**

The notification stays there until I dismiss it manually.

**Comment by ylecollen** [comment]
Vifon : it should work, i will check later.

It might also require few seconds (or so) to let the server sends pushes. (the notifications are cleared with the push)

**Comment by Vifon** [comment]
Do you mean the Android notification in the notification shade or the "unread" marker in the app itself? I mean the former, sorry for not clarifying.

**Comment by ylecollen** [comment]
Vifon,

both of them
1- the notification in the android application notifications (shared with any other notified applications)
This notification should disappear

2- the unread marker in the application should also be cleared at next launch (if not yet launched)  or refreshed (if the application is launched)

**Comment by Vifon** [comment]
I've tested it a bit more and it seems both notifications disappear reliably only when Vector is the foreground application. I don't use Greenify or similar mechanisms on it, which could interfere with the push message. I think a few times it disappeared when I had my phone just unlocked (without Vector actively running) but I couldn't reliably reproduce it.

The unread marker works properly, only the Android notification has issues.

How can I gather meaningful logs about this behavior?

**Comment by ylecollen** [comment]
once you've got it, open the application and send a bug report (hamburger icon). The logs should help us to investigate your issue (if you tell me which message is concerned, it would be nice)

**Comment by Vifon** [comment]
Ok, I've just sent the report with a brief description. The notification disappeared only when I opened the app to send the report.

**Comment by ylecollen** [comment]
I found one use case
0 - kill the application
1- got a notified message
2- read the message from another client
13:29
-> the push was stuck

**Comment by ylecollen** [comment]
Fixed with 
https://github.com/vector-im/vector-android/commit/ea63ac3e217f52b416f61b03677840cd09139864
