### ISSUE TITLE
Heavy battery drain.

### ISSUE THREAD

**Issue by DatGizmo** [vector-im/vector-android#167]
Setup:

Android 5.1 (CM12.1)
GSMCore 0.2.2 from microG, as a replacement for Google play services. (https://github.com/microg/android_packages_apps_GmsCore)
I recently switched to the microG apps/services instead of the Google play ones.
On my mobile there is a heavy battery drain by matrix. 

As long as the event-service from the vector app is not running, everything is fine.
When I receive a message, the app is woken via the GCM, and the event-service is started.
Now, for me it seems, that the event-service is used, which then keeps waking up the mobile network, causing the heavy battery drain.

Is there some kind of fallback to the notification service if there are issues with GCM?

Note: On my tablet, I don't have this issue with the same setup. But as the tablet is losing the Wifi connection sometimes during the day, I'm not sure if the two devices are comparable.

I've also reported this issue to the "matrix-android-console" as I'm facing the same issue there. (https://github.com/matrix-org/matrix-android-console/issues/24)
But got no response there.

**Comment by ylecollen** [comment]
When GCM is disabled, the android client fallbacks to a polling thread which drains battery
We never tested with GSMCore so we don't the application behaviour.

**Comment by DatGizmo** [comment]
Do you think this bug is probably more on your side, or is it more on the end of GSMCore?
Just asking, if I should also fill a bug on the GSMCore repo.

If I can provide you with some more detailed debug info. I'll gladly do so, but I might need some guidance, because I've not done this.

**Comment by ylecollen** [comment]
I really don't know which is responsible ?

Could you send a bug report ?

**Comment by DatGizmo** [comment]
I'll opened an issue at android_packages_apps_GmsCore. 
Will keep you updated.

**Comment by abrahimladha** [comment]
@DatGizmo  If you get this working please let me know. Im trying to get vector-android pushed into Fdroid
https://f-droid.org/forums/topic/vector-a-polished-matrix-chat-client/

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/6b6190b52c71ed7806c5981d477958c93148195d
