### ISSUE TITLE
Messages: Add Directory section at the top on scroll down

### ISSUE THREAD

**Issue by giomfo** [vector-im/vector-android#172]
Directory section should be displayed by default in Messages when recents list is empty. 

When recents is not empty, Directory section should appear when user scrolls down from the top.
Hide it by default when view controller appears.

**Comment by ylecollen** [comment]
Currently, there is no empty recents page

-> the directory is displayed when there is no room to avoid having an empty screen

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/183b6450695bd66081b5ae4f8fc6e2ff01bea095
