### ISSUE TITLE
Universal link failed if App removed from task stack

### ISSUE THREAD

**Issue by pedroGitt** [vector-im/vector-android#188]
When the App is removed fromt the task stack, a press on a room universal link does not launch Vecto on the correspnding room. Only "Messages" UI is displayed.

- Issue steps:

1. Start Vector App anget logged ot a valid user
2. On the device display the task stack (ex: Home button long press)
3. Remove the Vector form the stack
4. Go to the mailer to click on an universal link (ex: https://vector.im/develop/#/room/#RennesConnection:matrix.org)
5. Vector App stars but kept stuck in the "Messages" UI, the target room is not displayed

- Expected result: In step 5 the target Room should be displayed.
- Note: if the Vector App is not removed from the stack, there i no issue
- Version: master#13 03-Jun-2016 08:07

**Comment by pedroGitt** [comment]
The same issue is raised with the PermaLinks instead of the universla link.. likely a common root issue.

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/74b4755f76008446b994d1bdb9de192455f66991
