### ISSUE TITLE
Sharing from some apps to Vector not working

### ISSUE THREAD

**Issue by firecat53** [vector-im/vector-android#212]
Verizon Motorola MAXX (Android v 6.0).

Some apps share correctly (Contacts, Gallery, Leafpic, Smugmug), but other apps are not sharing correctly with Vector. They just open up Vector but don't prompt for a room to share with:

- Firefox
- Spotify
- Google+
- Slide (Reddit app)
- Simpletask
- IMDB
- Maps
- Shazam
- Youtube

Thanks!
Scott

**Comment by ylecollen** [comment]
Same issue with contacts
https://github.com/vector-im/vector-android/issues/208

**Comment by ylecollen** [comment]
Should be fixed with https://github.com/vector-im/vector-android/commit/1c8a380f8529dcb0ab01c0be78626f1d36cb7aec
