### ISSUE TITLE
Notification settings not working properly

### ISSUE THREAD

**Issue by Caerdwyn** [vector-im/vector-android#254]
When turn on the switch for "Enable notifications for this device", it appears to stay on as if the setting took effect, but if you go back to the main Messages screen, then back into Settings, the setting is disabled again. Whichever device I am signed into at the moment is also missing from the Notification Targets area near the bottom of the page.

**Comment by ylecollen** [comment]
This issue was triggering with an official ROM.
The GCM or server registration does not display an error or a spinner.
The behaviour will be updated

**Comment by pedroGitt** [comment]
Would it be possible to send a bug report ("Send Bug Report" item in the slider menu)?
As you mentioned, *"turn on the switch for "Enable notifications for this device""*, and then send the bug report please.
It would permit to figure out what is going wrong from this point on..

**Comment by Caerdwyn** [comment]
A bug report has been sent after toggling the settings.

**Comment by pedroGitt** [comment]
Looks like there is a network error...

**Comment by ylecollen** [comment]
06-26 21:40:23.173 18487 18487 E GcmRegistrationManager: registerPusher onNetworkError failed to connect to home.rdash.in/71.58.158.161 (port 8448) after 15000ms: isConnected failed: EHOSTUNREACH (No route to host)
06-26 21:40:23.173 18487 18487 E GcmRegistrationManager: fail to register @eaburdick3:home.rdash.in (failed to connect to home.rdash.in/71.58.158.161 (port 8448) after 15000ms: isConnected failed: EHOSTUNREACH (No route to host))
06-26 21:40:23.173 18487 18487 D GcmRegistrationManager: registerSessions : onSessionRegistrationFailed @eaburdick3:home.rdash.in

**Comment by ylecollen** [comment]
Do you have some connection issues on your server ?
But, we have something to improve.

**Comment by Caerdwyn** [comment]
Not that I'm aware of... my phone and computer are connected to Matrix all day and night without issue that I can tell... the only thing I remember having downtime for in the past 2 days is I upgraded synapse the other night, but I wouldn't think that would be causing that many errors?

**Comment by ylecollen** [comment]
do you have any trace on server side ?
The android developpers cannot help you to fix this issue if it is a server issue.
Do you have some traces on server to investigate if the GCM registration was done ? you have the date & time in the logs we posted here.

**Comment by Caerdwyn** [comment]
I failed to think about this before filling this report, but this was happening with synapse v0.16.0-rc1 at the time. Last night I upgraded to master v0.16.1, and as of right this minute, it seems to be working fine... I'll keep messing around with it a bit and close it if I find its fixed.

**Comment by ylecollen** [comment]
Assume this issue can be fixed because we didn't get any news from the last 2 weeks.
