### ISSUE TITLE
make "turn the screen on for 3 seconds when a notification is received" configurable

### ISSUE THREAD

**Issue by 4nd3r** [vector-im/vector-android#255]
1a57f8d was a bugfix? Sorry, but this default behaviour is annoying.

**Comment by taaviilves** [comment]
In version 0.3.2 (116c3b7) during active chat in browser phone keeps turning the screen on when a new message is received.

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/3a82249de2abb839ce7ecc0796773e3c9097a1a1
