### ISSUE TITLE
The app should not display <img> from HTML formatted_body

### ISSUE THREAD

**Issue by manuroe** [vector-im/vector-android#261]
Before displaying html from formatted_body,  Vector web sanitises it by keeping only html tags defined in a whitelist.
We should do the same on mobile apps.
More explicitly, Android should not display <img>.

For info, vector web sanitises like this:
https://github.com/matrix-org/matrix-react-sdk/blob/24223ae2b69debb33fa22fcda5aeba6fa93c93eb/src/HtmlUtils.js#L24

**Comment by ylecollen** [comment]
Should be fixed by
https://github.com/vector-im/vector-android/issues/261
