### ISSUE TITLE
Room Settings: Add "Addresses" section

### ISSUE THREAD

**Issue by giomfo** [vector-im/vector-android#264]
The user must be able to check the existing addresses (alias), and create new ones.

Add a notice "To link to a room it must have an address." when the user let anyone who knows the room's link access the room, whereas no address is defined

**Comment by oddvar** [comment]
also list the room ID in there please

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/3f9069873fdc1693df5dadfb7133be7fc361c177

**Comment by cuhkrain** [comment]
It is highly appreciate that you provide an example for the room id.... the end users will lost here.
