### ISSUE TITLE
Accepting an invite does not get full scrollback

### ISSUE THREAD

**Issue by Kegsay** [vector-im/vector-android#271]
I accepted an invite from Matthew and I got history up to the point I was invited (I did NOT get the invite message itself). I complained that I didn't have full history (thinking this was a room setting) and it turns out it was not a room setting: `"history_visibility": "shared"`. The room was a federated room.

Expected: I should have received the full room history from *before* I was invited, but I did not.

Version: 0.3.1 `44b60da`

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/1f52b584f3bc53128d3a159008fb64d1d9de1c58
