### ISSUE TITLE
Impossible to scroll in User list 

### ISSUE THREAD

**Issue by rubo77** [vector-im/vector-android#302]
When selecting details in a room and from there **people** it is nearly impossible to swipe down without selecting the user on which your finger started the swipe

**Comment by rubo77** [comment]
This is still annoying, it's not really possible to scroll down, if there are more than 5 people in the room

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/32422f638e181d3ade8a1320ea42895ad7b36a7c

**Comment by rubo77** [comment]
Thanks 
:+1
When will this be released in the Play Store?
