### ISSUE TITLE
[Search Screen] add real time search result

### ISSUE THREAD

**Issue by pedroGitt** [vector-im/vector-android#306]
In the search screen for the "ROOMS" category add the capability to display the results as the user is typing. 

Steps:

1. from the "MESSAGES" screen press the loop icon to acces the search screen
2. in the ROOMS tab, start typing in the search entry area
3. the results should be updated in real time according to search entry area content

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/3bb9ce4626aceb8d7c0e0e0bbd93409c7541a6f5
