### ISSUE TITLE
Room header view seems to ignore the first tap

### ISSUE THREAD

**Issue by pedroGitt** [vector-im/vector-android#310]
Room header view seems to ignore the first tap that should expand and shrink.

Ref: https://vector.im/develop/#/room/!TfGOBljmIFILPqKYwQ:matrix.org/$1468433215391363arHdS:matrix.org

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/3f4101266b35efcd8f6d938ce107c3402a9b4010

The header was not expanded because the keyboard was expanded.
The behaviour is updated to have the same behaviour as the IOS client.
