### ISSUE TITLE
Quick replay on invitations to room

### ISSUE THREAD

**Issue by hurzelmann** [vector-im/vector-android#334]
when receiving a invitation to a room and open the quick reply function in the notif I am able to insert some text but I am not able to accept the invitation.

The text actually gets lost.

**Comment by ylecollen** [comment]
The quick reply should have been been displayed.

The user has to join the room by clicking on open.

fixed in https://github.com/vector-im/vector-android/commit/0921143012abde0bea6dabc3dcbb3cffd15db0f9
