### ISSUE TITLE
Add option to disable the permanent notification when background sync is on.

### ISSUE THREAD

**Issue by Ram-Z** [vector-im/vector-android#362]
I don't want to have any active notification for things that don't require my attention.

**Comment by ylecollen** [comment]
It is an android requirement (we use a foreground service).

-> If we don't use a foreground one, you might loose many messages because Android kills background services.

So, if you don't want this permanent notification, disable the background sync.

**Comment by Ram-Z** [comment]
> It is an android requirement (we use a foreground service).

Hm.. I see.

> If we don't use a foreground one, you might loose many messages because Android kills background services.

All I really care about is getting notified when I'm mentioned, etc. The Telegram app seems to be able to do this without keeping an active notification. Can their approach not be used for this application?

> So, if you don't want this permanent notification, disable the background sync.

Unfortunately, the side-effect of that is that it would... **disable background sync**. :disappointed:

**Comment by ara4n** [comment]
@ylecollen surely the problem here is that GCM isn't being correctly enabled (which is why it is shifting to using background sync?)

**Comment by ylecollen** [comment]
i assume it is the fdroid version.

**Comment by ara4n** [comment]
@Ram-Z are you on fdroid or play store?

**Comment by tetris4** [comment]
Fwiw, I am using the fdroid version and I can replicate what Ram-Z is experiencing. I would really appreciate an option to disable this. 

I don't really know how telegram, kontalk and libresignal implement it, but I have them installed and working properly and they do not show a constant icon in the notifications. 

Hope this helps. =)

**Comment by Ram-Z** [comment]
Yes I'm using the FDroid version. Does the Play Store version behave differently?

I'm also using the FDroid version of Telegram.

**Comment by pedroGitt** [comment]
Yes the PLayStore version behaves differently. Since it uses GCM,  once in  bakground, the service does not need to be set as a foreground process, so no permanent notification is displayed.

**Comment by Ram-Z** [comment]
Indeed, the Play Store version seems to not have the permanent notification. Would it be possible to check for GCM availabitily in the FDroid version and if it's there use it?

I guess I could also just use the Play Store version.

**Comment by ylecollen** [comment]
F-droid -> no GCM : it is a requirement to publish on F-droid (the application is not compiled with the GCM libs).

**Comment by pedroGitt** [comment]
FDroid is a FOSS dedicated store, so no dependency to non open source SW..

**Comment by ylecollen** [comment]
kontalk ::MessageCenterService : this service is not a foreground one so it could be killed.

**Comment by silvio** [comment]
Can we change the icon if messages are appeared?

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/63b95e5c5f9a5434f6559aeb974506dd541e6cac

The "listening for events" notification is now hidden from the status bar (it will be displayed when swipping the status bar).
