### ISSUE TITLE
searching for "oddvar" in people crashed the app

### ISSUE THREAD

**Issue by oddvar** [vector-im/vector-android#37]
reproducable

**Comment by ylecollen** [comment]
I don't reproduce your issue : i searched Oddvar without getting any crash.

Could you submit a bug report ?

**Comment by oddvar** [comment]
sent - but this issue was fixed by upgrading to latest, as suggested. thanks!

**Comment by ylecollen** [comment]
fixed in 
https://github.com/vector-im/vector-android/commit/59fdf4fc57d935e6de1985c9bca73e16f4492caa
