### ISSUE TITLE
Sender picture missing in notification

### ISSUE THREAD

**Issue by pedroGitt** [vector-im/vector-android#386]
In the push notification content, the picture of the sender is not displayed. Instead, the default avatar is always displayed. 
Version: 0.4

**Comment by ylecollen** [comment]
https://github.com/matrix-org/matrix-android-sdk/commit/71614342af14fec53192575ca38da6b3bf71d8d1
https://github.com/vector-im/vector-android/commit/c3ccc556ac9113124aac5d1654b6b3b3f20c26b1
