### ISSUE TITLE
Displayed name should be consistent for all events

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/vector-android#396]
Under certain circumstances the displayed name on join events is different from subsequent messages.

Screenshots and more info: https://vector.im/beta/#/room/!GnEEPYXUhoaHbkFBNX:matrix.org/$147188242541349iIaeP:matrix.org

See also: https://vector.im/beta/#/room/!cURbafjkfsMDVwdRDQ:matrix.org/$14717754291ZiEsz:machinespirit.net

**Comment by ylecollen** [comment]
I don't how to reproduce the issue. 
I analysed the code and i fixed the only reasons which could provide a stale display name.

**Comment by Matrixcoffee** [comment]
(For future reference)

The easiest way to reproduce is to simply visit the permalink:

https://vector.im/beta/#/room/!cURbafjkfsMDVwdRDQ:matrix.org/%2414717754291ZiEsz:machinespirit.net
