### ISSUE TITLE
Generated avatar should be consistent for all events

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/vector-android#397]
Avatar is generated from the first character of the mxid on joining, but in subsequent messages uses the first character from the display name.

Screenshot: https://vector.im/beta/#/room/!GnEEPYXUhoaHbkFBNX:matrix.org/$147188641153782LDUiI:matrix.org

Version 0.4.0/f-droid

**Comment by ylecollen** [comment]
The avatar computation did not use the same display name than the notice text.
It used to use the matrix Id where as the join event display should have been used.
