### ISSUE TITLE
Inbound calls can still get stuck in a state where you can't decline them

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-android#400]
Might be specific to m.call.invite's appearing in group rooms, but i thought i'd seen vdh suffer this too.  See https://vector.im/develop/#/room/!DgvjtOljKujDBrxyHk:matrix.org/$14718987041116kwLne:ralith.com for specifics

**Comment by richvdh** [comment]
I think what I've seen is that, if Vector is backgrounded, the device is notified for the new call, but *isn't* notified if you pick up the call on another device. So the first device keeps ringing and is generally confused

**Comment by ylecollen** [comment]
duplicate of https://github.com/vector-im/vector-android/issues/437
