### ISSUE TITLE
Sending message with # in markdown in backticks ends up with the #'s being escaped by backslashes

### ISSUE THREAD

**Issue by giomfo** [vector-im/vector-android#405]
Example: send "test \`toto #123\`" from vector android
the formatted body will be "test <code>toto \\#123</code>"
instead of "test <code>toto #123</code>"

Related to https://github.com/vector-im/vector-ios/issues/522

**Comment by ylecollen** [comment]
fixed in https://github.com/vector-im/vector-android/commit/d7fef292260639f6c904c3b466c7d6619c563db1
