### ISSUE TITLE
Vector shouldn't expose Directory when trying to scroll past the bottom of the room list

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/vector-android#418]
When scrolling past the top of the room list, Vector exposes the "Browse directory" option at the top of the room list. This is normal and expected.

However, the same thing happens when trying to scroll past the *bottom* of the room list, causing a jump in view position.

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/783343bb56e8ea9549728ce01b2a737a0f6695df
