### ISSUE TITLE
Rendering room preview shouldn't take forever

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/vector-android#421]
https://vector.im/beta/#/room/!cURbafjkfsMDVwdRDQ:matrix.org/$1472143176241991GwwCA:matrix.org

https://vector.im/beta/#/room/!cURbafjkfsMDVwdRDQ:matrix.org/$1472166308312581oohli:matrix.org

**Comment by ylecollen** [comment]
It works properly on my side but it might require several seconds because MatrixHQ room has a lot of members.

Your device RAM is quite limited (512MB) so i suspect that there are many GC.

**Comment by Matrixcoffee** [comment]
We're not talking a few seconds here. I haven't had the patience to wait longer than 5 minutes, and it has never completed for me. I don't understand what the big difference is here. Actually joining the room takes a couple of seconds, so why does the preview take so long and why would memory suddenly be an issue?

Just tried to open a room with 22 users at 17:45 and waited till 17:51, then did a rageshake. I left it for you in private.

**Comment by ylecollen** [comment]
According to the device logs, it seems that the server response is never received.
The device has not enough free memory to manage it properly.

08-29 17:36:59.671  8726  8726 E Memory usage: ---------------------------------------------------
08-29 17:36:59.671  8726  8726 E Memory usage: usedSize   9 MB
08-29 17:36:59.671  8726  8726 E Memory usage: freeSize   0 MB
08-29 17:36:59.671  8726  8726 E Memory usage: totalSize  9 MB
08-29 17:36:59.671  8726  8726 E Memory usage: ---------------------------------------------------
08-29 17:36:59.673  8726  8726 E Memory usage: availMem   87 MB
08-29 17:36:59.673  8726  8726 E Memory usage: totalMem   466 MB
08-29 17:36:59.673  8726  8726 E Memory usage: threshold  56 MB
08-29 17:36:59.673  8726  8726 E Memory usage: lowMemory  false
08-29 17:36:59.673  8726  8726 E Memory usage: ---------------------------------------------------

**Comment by ylecollen** [comment]
https://github.com/matrix-org/matrix-android-sdk/commit/2ed84ed78fa2854ad00041e591ea0f040c9d4b7b
