### ISSUE TITLE
Intercept matrix.to URLs within the app

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-android#423]
Vector/Web now generates permalinks as matrix.to URLs.  Therefore we need to (urgently) recognise matrix.to URLs within the app and follow them within the app rather than linking out to the matrix.to website.

https://github.com/matrix-org/matrix-react-sdk/commit/ad873c2b60c1b7fead2b20975a66c6dc6cec06cc#diff-43ba768343dac45fa03389f245f80e39R106

...is the equivalent commit for vector-web.

(see also https://github.com/vector-im/vector-ios/issues/547)

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/89687041d2cdcd4cf6336c401e344d6523f35dc4
