### ISSUE TITLE
Answering a call on desktop whilst also ringing on android causes android to ring forever unstoppably

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-android#437]
The only way to stop it from ringing is to force-terminate the app.  This has been the case for almost a year now.  @richvdh thinks the problem is that if the app is backgrounded, it doesn't get the answered notification, and so doesn't know to terminate the ringing.  At the least, launching the app should give the user a way of cancelling any ringing calls.  We should also time out ringing locally if needed.

**Comment by ylecollen** [comment]
Richvdh used an old version (0.3.3).
Many infinite ringing issues have been fixed in version 0.4.0. (google play release)
