### ISSUE TITLE
Unable to join federated rooms with Android app

### ISSUE THREAD

**Issue by benhylau** [vector-im/vector-android#445]
I am connecting through a self-deployed homeserver. Through the web interface I am able to join federated rooms, and the Android app would sync up and everything works properly. But if I try to directly join a federated room through the Android app, it gives me an error because the app thinks the room has zero member and says I cannot join an empty room.

![screenshot_20160901-214147](https://cloud.githubusercontent.com/assets/2261308/18190035/76da050a-708d-11e6-851c-11b466461ea9.png)

**Comment by ylecollen** [comment]
Could you send a bug report ?

**Comment by benhylau** [comment]
@ylecollen Hey I built `develop` with your fix and am able to join federated rooms now. Thanks for addressing this so quickly!

Homeserver is `matrix.tomesh.net`
