### ISSUE TITLE
On create room, it should go to add members screen directly

### ISSUE THREAD

**Issue by sim6** [vector-im/vector-android#448]
When I create a room, the room is created as empty room. I think a empty room doesn't make sense, so always I go to add members screen. Please, could be this step automatic.

**Comment by ylecollen** [comment]
Sim6,

it is an expected behaviour.

We're going to implement a second room creation page in which you will add members before creating it.

So, when you will tap on the (+), you will have choice to create an empty room or select members to invite in the created room.

**Comment by sim6** [comment]
Ok, thanks!
