### ISSUE TITLE
faster procedure for private one2one conversation - UX improvement

### ISSUE THREAD

**Issue by xavierle** [vector-im/vector-android#453]
actually to send a message to your favorite contact

you have first to create a room which is public default
to decide this room to be private
then to look for your contact
then to invite your contact to your room

this is not very similar to usual habits.

on usual apps, you go to look for a contact and you can directly start a private one to one conversation with that contact.

additionnaly you can invite other contacts to the private discussion or
you can also do create a room as in the matrix/vector way.

the procedure is very fine for multi user rooms

but i would recommend to create a more direct procedure to start one to one private discussions.

actually our users prefers to keep with xmpp app because of this sort of UX issues
even if vector integrated better functions like voice and video.

users fears to create a public room by mistake when they want to have a private talk.

**Comment by ylecollen** [comment]
BY default, 
1- the rooms are private by default.

2- you can start a chat from an user by searching him/her in your contacts, tap on the avatar and press "Start chat"
