### ISSUE TITLE
Better UI to differentiate editable and non-editable room details

### ISSUE THREAD

**Issue by ylecollen** [vector-im/vector-android#477]
the user cannot have the permission to modify them.

**Comment by RajPratim21** [comment]
I am new to vector but very interested to work on it here is UI I designed
How about this ,
I am working to add some more features too like different background shades for the user to whom the account belongs. please comment !!!!!
![screenshot_2016-09-17-15-14-06](https://cloud.githubusercontent.com/assets/15442871/18607632/e5f9380c-7cef-11e6-8190-7088e532f5c9.png)

**Comment by RajPratim21** [comment]
i have merged a pull request for it too #524

**Comment by RajPratim21** [comment]
i have a pull request to for above #524
