### ISSUE TITLE
Prevent sending emty message from the quick reply notification

### ISSUE THREAD

**Issue by pedroGitt** [vector-im/vector-android#49]
**Issue description:**
1. receive a push notification
2. click on the notification and scroll down to make appear the "Quick Reply" action
3. press on "Quick Reply"  action
4. even if the message is empty, the message can be sent

**Expected behaviour:**
the "sent arrow" should be disabled if no message is typed

**Comment by ylecollen** [comment]
It has been merged on develop branch
