### ISSUE TITLE
[VoIP] crash in caller side when a started video call is stopped asap

### ISSUE THREAD

**Issue by pedroGitt** [vector-im/vector-android#501]
The caller side crash on a video call, when right after starting the call, the hang up button press is pressed asap..

**Steps:**
1. Start a video call
2. Immediatley press the hang up button to cancel the call
3. a crash (libc: Fatal signal 11 (SIGSEGV)) is triggered

**Comment by pedroGitt** [comment]
Reproduced on Moto G.
Race condition..
The video context in webRTC lib was cleared, but after the video API was still called.

**Comment by root562** [comment]
I have encounter this problem again on two different devices that I have tested. Video call crash the app at hangup. Is this still the same race condition. PS: I am new to android programming.

**Comment by root562** [comment]
I posted this before https://github.com/vector-im/riot-android/issues/3311#issuecomment-533945105
Tracing the Riot 0.9.6 code for the bug. It happens at CallsManager.Java, onHangup(). mActiveCall.hangup() cause the program to crash. This is a call to SDK. The code is not in Riot 0.9.6. Can someone doing the matrix-android-sdk check what is happening inside IMXCall.hangup()?
How do I forward this to matrix-android-sdk thread?
