### ISSUE TITLE
Add the ability to swipe right to go back to the room list

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-android#527]
(like ios)

**Comment by ylecollen** [comment]
I'm not sure it the android of doing thing

**Comment by ara4n** [comment]
If viber & telegram do this, we should consider it too - also for consistency with iOS.  See #1871

**Comment by Matrixcoffee** [comment]
IIRC it was backed out due to oversensitivity, making it difficult to scroll normally.
