### ISSUE TITLE
Quoting : displays "null" on membership events

### ISSUE THREAD

**Issue by jeangb** [vector-im/vector-android#549]
Whereas I quote a membership event.
To reproduce :

- On a membership event, hit quote on the context menu
- The event isn't displayed, instead "null" is diplayed

![quoting membership](https://cloud.githubusercontent.com/assets/22364949/18756195/4c310b10-80ef-11e6-9e89-d8757d4f8d57.png)

Version is 0.5.2 (d20f5b)

**Comment by Matrixcoffee** [comment]
I reproduce this. (And am amazed that it doesn't just crash. Good job there.)
