### ISSUE TITLE
vector.im/{beta,staging,develop} and riot.im/{app,staging,develop} permalinks should work as well as matrix.to ones

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-android#560]
It looks like we might have stopped picking up non-matrix.to permalinks in the app?

**Comment by ylecollen** [comment]
Weird
https://vector.im/develop/#/room/#irc_#matrix:openmarket.com/$147489683046681qGbJa:matrix.org
https://riot.im/beta/#/room/#irc_#matrix:openmarket.com/$147489683046681qGbJa:matrix.org
https://vector.im/beta/#/room/#irc_#matrix:openmarket.com/$147489683046681qGbJa:matrix.org
https://riot.im/staging/#/room/#irc_#matrix:openmarket.com/$147489683046681qGbJa:matrix.org
https://vector.im/staging/#/room/#irc_#matrix:openmarket.com/$147489683046681qGbJa:matrix.org
