### ISSUE TITLE
URLs containing $s aren't linkified correctly

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-android#561]
See https://matrix.org/_matrix/media/v1/thumbnail/matrix.org/ChsCwbLTHJOZeXNpGYpbmPqz?width=800&height=600

**Comment by ylecollen** [comment]
Android does not support $ in URLs.
IOS does.

**Comment by SijmenSchoon** [comment]
A solution is URL escaping them, then

**Comment by ylecollen** [comment]
The android client already does.

**Comment by SijmenSchoon** [comment]
Well clearly it doesn't, considering it's $147... instead of %24147

**Comment by ylecollen** [comment]
SijmenSchoon  : Android url encodes the permalinks it sends not the ones it receives.

The other clients don't URL encode them when copying to the buffer.

**Comment by ylecollen** [comment]
Add a regex to display them properly.
