### ISSUE TITLE
Sync without GCM

### ISSUE THREAD

**Issue by steckerhalter** [vector-im/vector-android#578]
I have installed the app via F-Droid and found this in the FAQ: https://matrix.org/docs/guides/faq.html#i-installed-vector-via-f-droid-why-is-it-draining-my-battery

This seems to be true in that it really drains my battery. AFAIK many Android apps handle this differently in that they sync via an account. Android then manages the syncing without the app having to poll or use GCM.

I think this would be the alternative to GCM which doesn't drain the battery. I'm not an Android expert but noticed that many apps doing that. So maybe you could consider this? Thanks for the hard work and everything.

**Comment by ylecollen** [comment]
steckerhalter 

Did you read how to reduce this battery draining ?
have a look in the settings page 
-> you can reduce the sync heartbeat when the application is in background
-> you can add a delay between two syncs when the application is in background
-> you can disable the sync when the application is in background

you can also install MicroG to replace GCM (you will need to install the "standard" version).

**Comment by steckerhalter** [comment]
@ylecollen no, is it described somewhere already? Thanks, I will probably look into using microG.

**Comment by steckerhalter** [comment]
I digged a bit deeper into the drain and I think it probably wasn't much related to Riot really, sorry for the noise and thanks for the suggestions
