### ISSUE TITLE
Terms and conditions : url links are not found

### ISSUE THREAD

**Issue by jeangb** [vector-im/vector-android#580]
To reproduce :

From the sidebar menu, go into the Terms and conditions
Try some of the url linked : https://matrix.org/_matrix, etc
"Method Not Allowed". The website isn't displayed.

Same problem on vector-ios : https://github.com/vector-im/vector-ios/issues/670

**Comment by ara4n** [comment]
I'm very confused by this - the URLs should be:
 * https://riot.im/privacy
 * https://riot.im/tac
 * https://riot.im/copyright
It's a major problem if they're wrong - @ylecollen, please can you fix?

**Comment by ylecollen** [comment]
The privacy, tac and copyright are the right URLs but the links in theses pages are invalids.
