### ISSUE TITLE
Leave room too hidden

### ISSUE THREAD

**Issue by sim6** [vector-im/vector-android#587]
Please, could you display a leave room button more accessible?

**Comment by ylecollen** [comment]
Where do you think if it should be more visible ?

**Comment by Matrixcoffee** [comment]
May I suggest the menu? (Top right.) The menu has only one entry ("Room Details") right now.

**Comment by ylecollen** [comment]
it is added in the menu like Coffee suggested.

**Comment by sim6** [comment]
Thanks!
