### ISSUE TITLE
Email validation token is sent even to invalid emails

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-android#590]
I receive an email validation token even if my email is not associated with a matrix account. Very very confusing, email validity check should be done before the email is sent

**Comment by ylecollen** [comment]
https://matrix.to/#/!zOmsiVucpWbRRDjSwe:matrix.org/$14754844271806648vYjqr:matrix.org

**Comment by ylecollen** [comment]
The steps to reproduce 
-> Go to the reset password page (login page)
-> Enter an email address which is not linked to a matrix account

The client should check if the email is known before sending the reset password request.
