### ISSUE TITLE
Viewing mubot images in fullscreen shows black screen

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/vector-android#601]
Screenshot & rageshake sent in private - applies to release and develop version - example: https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/%2414757027592524974BSZqE:matrix.org

**Comment by ylecollen** [comment]
The high res picture has no mimetype.

**Comment by Matrixcoffee** [comment]
Does the low res picture have a mimetype? If so, is this a bug in Synapse?
