### ISSUE TITLE
Direct chats are not shown as low priority even though they are

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/vector-android#662]
Riot-Web and Riot-Android have a difference of opinion on where to put low-priority Direct Chats. Web puts them in the low priority section, while Android puts them in the people section, and worse, fails to show a checkmark next to De-prioritize, as shown in the screenshot.

![wxatykmcolttwehmwdtzigmb](https://cloud.githubusercontent.com/assets/21172059/19944405/b836aebe-a133-11e6-9076-c78a2b06ea5a.png)

**Comment by ylecollen** [comment]
The people section will be removed so this issue won't exist anymore.
