### ISSUE TITLE
Don't prompt for additional permissions every time you open room details

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-android#669]
If the user doesn't want to give the app permissions to access contacts (or whatever the request is), don't prompt them constantly for it. We should let them manage it in Settings or similar

**Comment by Matrixcoffee** [comment]
This bug relates to what was discussed here:

https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/%2414781926871697198ZYFsr:matrix.org

**Comment by ylecollen** [comment]
I answered here
https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$14781931331699218FFlRz:matrix.org

On android >= 6.0 device, the user has to tell to never ask again.
The permissions are managed by Android not by the application.
