### ISSUE TITLE
 Empty avatar placeholder in the incoming call layout

### ISSUE THREAD

**Issue by jeangb** [vector-im/vector-android#674]
To reproduce:
- Receive a call from a user with no photo
- In the incoming call layout, the avatar is empty (just green, with no letter)

![incomming call no placeholder avatar](https://cloud.githubusercontent.com/assets/22364949/20007565/23bdf998-a29d-11e6-8260-79c880cd2916.jpg)
There is a letter in the 07.01 Call - No Avatars in zeplin
Version 0.5.3-dev (3e588a0)

**Comment by ylecollen** [comment]
We don't imply yet the new design.
