### ISSUE TITLE
Direct Messages : a 1to1 room is DM on 1 account and not on the other

### ISSUE THREAD

**Issue by jeangb** [vector-im/vector-android#677]
What's happened:
- Device 1 was on VectorAndroidDevelop version (with DM embeded)
- Device 2 was on VectorAndroid version (no DM)
- A room was created by device 1 and device 2 was invited to this room
- This morning I installed the last VectorAndroidDevelop on device 2.

The room is not seen as a DM room on device 1.
The room is seen as a DM room on device 2 since I installed the last androiddevelop version on it.

**Comment by ylecollen** [comment]
The first device was already used with the former Direct messages management so the new heuristic cannot be applied.
