### ISSUE TITLE
Unsupported TLS protocol version

### ISSUE THREAD

**Issue by babolivier** [vector-im/vector-android#680]
Hi,

I'm running a Synapse server behind a [Caddy](/mholt/caddy) web server acting as a reverse proxy. When trying to connect via the Android app, Riot displays a "Handshake failed" message.

You can see all details and reply from the Caddy developper at https://github.com/mholt/caddy/issues/1241.

**Comment by zackp30** [comment]
Getting the same issue.

**Comment by babolivier** [comment]
Hi there,

Any news on this? Anyone? I need this for internal usage in my organisation, and can't really think about moving from Caddy regarding our infrastructure.

**Comment by ylecollen** [comment]
Do you this isue during the login process ?
Could you send some logs ?

**Comment by ylecollen** [comment]
Could you create me an account on your home server ?
Most of the users don't provide us all configuration information

**Comment by ylecollen** [comment]
https://github.com/omise/omise-android/commit/26511ae3860cbf5aa55683297c6dafe9159ccb79

**Comment by ylecollen** [comment]
It should work from the version https://github.com/vector-im/vector-android/commit/fed6412c4ec25e461e6ae1744e48b13e6acef15b

i update okhttp from version 2.0.0 to version 2.7.5.
modern TLS is supported from version 2.2.0.

I have no way to test if it works with your servers so i close this issue because i'm sure that you will read my comments and test the updates.

**Comment by babolivier** [comment]
Hi @ylecollen, and sorry (really) for the lack of reply (busy week-end).

I have just updated Riot to v0.6.0 and it doesn't fix the issue (same error, on both sides). If you want to try it out by yourself, you can create an account on our Riot Web instance here: https://riot.trancendances.fr/

**Comment by babolivier** [comment]
Hi @ylecollen,

Quick update to say that I just updated Riot for Android to v0.6.3 and now everything works fine :smile:

Thanks all for the work 👍
