### ISSUE TITLE
[Direct Message] Room isn't view as a DM room by the invitee

### ISSUE THREAD

**Issue by jeangb** [vector-im/vector-android#692]
To reproduce:
- Create a 1:1 room using _new room (+) -> Start chat_ (I used an iPhone)
- Invite user2
- On the invitee device accept inviting request

On the invitee client, there is no "green little man" on the room.
According to https://github.com/vector-im/vector-ios/issues/713 it should.

Version 0.5.3-dev (20372b8)

**Comment by pedroGitt** [comment]
Done, waiting for validation

**Comment by jeangb** [comment]
Approved in 0.6.4
