### ISSUE TITLE
wrong device_id in m.new_device events

### ISSUE THREAD

**Issue by richvdh** [vector-im/vector-android#695]
m.new_device is supposed to contain the device id of the new device; in fact matrix-android-sdk seems to send a random device_id

**Comment by ylecollen** [comment]
The device id is a random one only if there was none defined by the home server.

On the latest android client, it is not possible to enable the crypto if there is no device id.

**Comment by richvdh** [comment]
I think this got fixed.

**Comment by ylecollen** [comment]
Right, it has been fixed for a long time
