### ISSUE TITLE
[Direct Message] Start chat with himself from member details create an empty room with error toast

### ISSUE THREAD

**Issue by jeangb** [vector-im/vector-android#702]
To reproduce:
- From a DM room with user1 and user2 (you are user1)
- Hit your profile (user1) and click on DIRECT CHATS / Start New Chat
- A toast appears "user1 is already in the room"
![start new chat from your profile](https://cloud.githubusercontent.com/assets/22364949/20349596/6dc62bb0-ac0b-11e6-904f-900ae4f2d6f8.png)

I expected a new room won't be created. However when I go back in the rooms list, an Empty room is created.
More important, each time you click on **Start New Chat**, a new **Empty room** is created.

**Comment by pedroGitt** [comment]
We follow the iOS behaviour:  an empty room is created but the message error is now removed

**Comment by pedroGitt** [comment]
Done, waiting for validation

**Comment by jeangb** [comment]
Approved in 0.6.4
