### ISSUE TITLE
[Direct Message] Crash on trying to untag Direct Chat from empty Direct Message Room

### ISSUE THREAD

**Issue by jeangb** [vector-im/vector-android#704]
To reproduce:
- Direct message room wither user 1 and user 2
- User 2 left
- With user 1, from the rooms list ; click on the context menu, and try to uncheck "Direct Chat"

Riot crashes
https://matrix.org/_matrix/media/v1/download/matrix.org/GVaOdikECSFNqyYGwPCUtVVM
Version 0.6.0-dev (40a2744)

**Comment by pedroGitt** [comment]
Fixed

**Comment by jeangb** [comment]
Approved in 0.6.4
