### ISSUE TITLE
[Direct Message] Direct chats list from member profile doesn't show all the direct chats

### ISSUE THREAD

**Issue by jeangb** [vector-im/vector-android#706]
I have 4 direct chat rooms with an other user. These rooms were created through the profile details page and the DIRECT CHATS / Start New Chat button.
When I open this user member details I see only 2 direct chats.

The DM rooms I have with riotuser10:
![dm rooms](https://cloud.githubusercontent.com/assets/22364949/20351353/c7298506-ac12-11e6-911f-eb3565ed1188.png)
The riotuser10 profile:
![member details](https://cloud.githubusercontent.com/assets/22364949/20351388/eaa6a450-ac12-11e6-9533-d86e8197af61.png)

Version is : 0.6.0-dev (40a2744)

**Comment by pedroGitt** [comment]
Done, waiting for validation

**Comment by jeangb** [comment]
Approved in 0.6.4
