### ISSUE TITLE
Crash on hitting tabs on search view

### ISSUE THREAD

**Issue by jeangb** [vector-im/vector-android#709]
To reproduce:
- From the rooms list, hit the search button
- Select MESSAGES or FILES tab

Riot crashes.
Logs : https://matrix.org/_matrix/media/v1/download/matrix.org/oItLJaucmzvylQGbilewWExW
Version 0.6.0-dev (40a2744)

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/1e8b21c97d00cb9f15ebafe057ad7f7c7f542e42
