### ISSUE TITLE
Instant crash on global message search

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/vector-android#711]
Reproduce: From the recents list, press the magnifying glass icon (search). Tap the «messages» tab. Crash.

**Comment by jeangb** [comment]
Related to https://github.com/vector-im/vector-android/issues/709

**Comment by ylecollen** [comment]
fixed https://github.com/vector-im/vector-android/commit/1e8b21c97d00cb9f15ebafe057ad7f7c7f542e42

**Comment by Matrixcoffee** [comment]
Fix confirmed. Thanks.
