### ISSUE TITLE
Improve adding member from search/invite page

### ISSUE THREAD

**Issue by jeangb** [vector-im/vector-android#712]
From the search / invite page (after starting a new chat and you want to invite a member), adding a member feels strange.
![searchinviteview](https://cloud.githubusercontent.com/assets/22364949/20386364/9a2e6464-acbb-11e6-8738-eafc6f87ae7d.png)

Indeed, hitting on the member name or the avatar aren't taking into account. However the status of the member, or the rest of the item will work.

Unless this is wanted, maybe we could fix it ?

**Comment by sachoosaini** [comment]
Yeah this is thing that force me to manually add people to my own group i created. Some users find it difficult to add users....

**Comment by ylecollen** [comment]
-> when the edittext is empty, the list of members is the 1:1 room ones.
-> if you search a member by a pattern, it will search by any known room member.

**Comment by ylecollen** [comment]
It was triggered because a long click listener was set on the username text and on the avatar (to copy the matrix id)
so, the clicks were ignored.

The userid can be copied with a long click on the username (member details page)

Theses long clicks are removed to avoid such weird behaviours.
