### ISSUE TITLE
Race condition on «send» button

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/vector-android#714]
When the UI locks up, and I press the send button multiple times (because the UI is not responding) it can happen that the message gets sent multiple times.

**Comment by ylecollen** [comment]
i've added an in the matrix sdk to avoid such lags.
The cryptostore management is the responsible of theses lags.

**Comment by Matrixcoffee** [comment]
Fixing the lags is good, but doesn't fix the race. Disabling the send button in the UI is not atomic.

**Comment by ylecollen** [comment]
it should better by now.

https://github.com/vector-im/vector-android/commit/5b1e1364c7ec2203f65b3c1fd9b9e53e514391a4

**Comment by Matrixcoffee** [comment]
Still not fixed. If my finger "stutters" on the screen, it can very quickly press the button twice, and send a duplicate message.
