### ISSUE TITLE
Inconsistent bolding of rooms with messages

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/vector-android#720]
In the below screenshot, #riot-dev clearly has unread messages, but is not bolded.

![jdftqcdixtxmrghwygjxebnu](https://cloud.githubusercontent.com/assets/21172059/20450439/9030fd5e-ade8-11e6-8de0-bd0ec468a029.png)

**Comment by ylecollen** [comment]
https://github.com/matrix-org/matrix-android-sdk/commit/6129879cce45ec72bfa0b9708d5a3f38b0bc4204
