### ISSUE TITLE
[UI Performance issue] UI response is too slow

### ISSUE THREAD

**Issue by wjhtinger** [vector-im/vector-android#726]
such as, enter a room, after click, it need about 1 second to switch to room activity....

**Comment by ylecollen** [comment]
it is a known issue when the rooms are encrypted.

Could you send a bug report ?

**Comment by ylecollen** [comment]
it should be better by now
https://github.com/vector-im/vector-android/commit/5b1e1364c7ec2203f65b3c1fd9b9e53e514391a4

**Comment by RektInPieces** [comment]
it's not

**Comment by bmarty** [comment]
We are working on it, it will be much better in a few weeks
