### ISSUE TITLE
[Devices section] "Internal error" when trying to delete with special caracters in password

### ISSUE THREAD

**Issue by jeangb** [vector-im/vector-android#728]
To reproduce:

1. Go into Settings -> DEVICES section
2. Hit a device item and hit on DELETE
3. In the Authentification form, use a "strange" caracter as a password. I put a heart: ♥. Available in the android keyboard. (authentification will work with caracters such as "]((':;," )

Spining view remains during 10s then a "internal error" toast appears.
Version 0.6.1-dev (e951ade)

**Comment by ylecollen** [comment]
It seems being a server side issue.
