### ISSUE TITLE
Unable to send messages in #megolm since build 810: Network error

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/vector-android#742]
I can no longer send messages into [#megolm:matrix.org](https://matrix.to/#/#megolm:matrix.org) with the latest f-droid builds.

It seems to fail during the key-getting (green) stage with an unspecified "Network error".

Working with @ylecollen, we found that the update from build 809 to 810 is what breaks it, which is commit fed6412c4ec25e461e6ae1744e48b13e6acef15b.

Over several tests, I have reproduced this 100% of the time. The only determining factor is whether I'm running 809 or earlier, vs 810 or later. Logging out *and* rebooting the phone didn't help either.

I have a terribly slow 64k internet connection. Even so, updating from 809 to 810 couldn't have change my internet speed.

Android 4.4.2, ipv4, and mobile data (capped at 64kbps).

![qsyvfmdyivrexgadoqxabvjl](https://cloud.githubusercontent.com/assets/21172059/20541218/2c78c684-b0f4-11e6-9b27-afc1d8b53847.png)

**Comment by ylecollen** [comment]
I don't reproduce this issue on my side with a device under android 4.4.2 (same version as Coffee's device).

The device logs show a timeout error (network).
