### ISSUE TITLE
Memory leak when opening a room

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/vector-android#754]
Opening a room from the recents list causes Riot's memory footprint to permanently increase by a small amount. Going back to the recents list does not release the memory, and opening the *same* room again causes another increase. Repeatedly opening the same room will quickly run up the memory, until the app crashes.

To demonstrate, this is what happens when I repeatedly tap on "Matrix HQ" -> back -> "Matrix HQ" -> back -> "Matrix HQ" -> back -> "Matrix HQ" -> back -> "Matrix HQ" -> back -> ...

![mmpwqjplludubwsivvxlichn](https://cloud.githubusercontent.com/assets/21172059/20635468/462cfd80-b355-11e6-8ad4-2bc9dd2f05d6.jpeg)

As you can see by the blue line, it took me about four minutes to get Riot close to the point of crashing. (It usually crashes at about 30% of memory on my phone.)

For contrast, this is me using Riot normally:

![dlfnvupbvktehgfaarjncuwf](https://cloud.githubusercontent.com/assets/21172059/20635507/b61b920a-b355-11e6-8243-d290ca94281a.jpeg)

I realize my phone has limited memory. However, having studies the app's behavour, I believe it should be able to run Riot well and indefinitely if all leaks like these are fixed.

**Comment by ylecollen** [comment]
Not sure it is a memory leak.
Java might not trigger a GC.
We don't manage the objects releases like in C/C++ (with maloc/ free)
We have to force the GC to check it

**Comment by Matrixcoffee** [comment]
I can confirm that recent fixes have greatly reduced long-term memory growth. I can run Riot for at least 2 days without stopping it, instead of barely 2 hours.

Thanks for your time and effort!
