### ISSUE TITLE
Android is splitting unicode char for foxtopic avatar

### ISSUE THREAD

**Issue by pedroGitt** [vector-im/vector-android#95]
- Avatar is not properly handled when the room name contains some unicode content
- Split should be on codepoint, not on byte

Permalink: https://vector.im/beta/#/room/!zOmsiVucpWbRRDjSwe:matrix.org/$14616724691091SYIuH:sw1v.org

Fix in JS: https://github.com/matrix-org/matrix-react-sdk/blob/master/src/components/views/avatars/BaseAvatar.js#L106

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/c75c4414b029d34229e73dde7748851c5a8fadd3
