### ISSUE TITLE
Verification email is sent when username is already taken

### ISSUE THREAD

**Issue by oddvar** [vector-im/vector-android#96]
Tried registering with the name "oddvar" - got an error saying username is already taken but also got a verification email.

**Comment by giomfo** [comment]
The client must send a register request with the username, the password and the bind_email flag before requesting a validation token by email.

**Comment by pedroGitt** [comment]
This issue has been fixed in the PR  [Add check for user in use #109 ](https://github.com/vector-im/vector-android/pull/109)
