### ISSUE TITLE
License page repeats itself

### ISSUE THREAD

**Issue by oddvar** [vector-im/vector-android#97]
The Ts&Cs page repeats the licence 5 times and includes a lot of text which I don't think should be there (see https://github.com/vector-im/vector-android/blob/master/vector/src/main/res/raw/all_licenses.txt#L180).

I think it should be sufficient to print the license once and say, in front: 
This app uses the following libraries, which are all licensed under the Apache 2.0 license: Matrix SDK, Pristine libjingle etc etc

<licence>

**Comment by pedroGitt** [comment]
OK I see, the license fie repeats the Apache license statement for each library..
So it could look like this, is it fine for you, **oddvar**?:

*This app uses the following libraries, which are all licensed under the Apache 2.0 licenseMatrix SDK, libjingle, Retrofit, okhttp, html-textview, anddown.*

*Apache License
Version 2.0, January 2004
http://www.apache.org/licenses/*

*TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
1. Definitions.
Bla bla..*

**Comment by ylecollen** [comment]
The design has been improved and seems making everyone happy.
